dist: trusty
language: node_js
node_js:
- "10"

deploy:
- provider: script
  script: bash .travis/build.sh
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+
- provider: script
  script: bash .travis/build.sh
  on:
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+
