dist: trusty
language: node_js
node_js:
- "10"

deploy:
- provider: script
  script: bash .travis/build.sh
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+
